### ISSUE TITLE
Algorithm code

### ISSUE THREAD

**Issue by amacgregor** [PuristWu/Identifying-gender#1]
The article [here](https://www.sciencedirect.com/science/article/abs/pii/S0168169923000108) and the idea look interesting and promising. I was wondering if the modified ResNet-50 algorithm will be available at some point

**Comment by PuristWu** [comment]
Thank you for your interest in our work! Now, the copyright of the software in question was only officially accepted on November 11, 2022 (Patent No. 202210873428.1), and as of this writing, it is still under review. Please forgive us for not being able to publish the source code until it is licensed.
If you are interested, all the code in this study was written based on Pytorch and you can try to compile it yourself. Thanks.
